server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1303122004
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:cinema-booking-secret-key-2024-must-be-at-least-32-chars}
  expiration-ms: 86400000